<?php
namespace MailPoetVendor;
if (!defined('ABSPATH')) exit;
// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return ComposerAutoloaderInit37dc04601d164039997c193f1a077ef9::getLoader();
